### ISSUE TITLE
timed rotator

### ISSUE THREAD

**Issue by senojeel** [MonkDev/monkcms-snippets#12]
I am trying to use the timed rotator code, but it skips the first slide. If I print the array $rotator_items, it will show the correct number of slides. 

I am not sure how to fix this. Any ideas?

**Comment by chrisullyott** [comment]
This commit fixes this issue:
https://github.com/MonkDev/monkcms-snippets/commit/6ac0512ec1a8072209f52b1093b8d5fbac982bde
