### ISSUE TITLE
Article Categories

### ISSUE THREAD

**Issue by bengoshow** [MonkDev/monkcms-snippets#18]
I'm filtering a list of Articles by Series and by Category, but in the results I would like each article to display ALL categories it's assigned to.

I've tried using **categoryX** but nothing is returned.

**Comment by bengoshow** [comment]
Sorry - context is when using the Content Class

**Comment by chrisullyott** [comment]
@bengoshow Actually I haven't been able to work around this yet. `getContent()` repeats the line for any `X` tag, and currently I have only added a sequence number to differentiate them.

```
Array
(
    [0] => Array
        (
            [title] => Love, Forgiveness, and Jesus
            [slug] => love-forgiveness-and-jesus
            [date] => 2010-12-06
            [category1] => News
            [category2] => Test 
        )
)
```

Using the plain `category` tag though, a list should be produced anyway:

```
Array
(
    [0] => Array
        (
            [title] => Love, Forgiveness, and Jesus
            [slug] => love-forgiveness-and-jesus
            [date] => 2010-12-06
            [category] => News, Test 
        )
)
```

**Comment by bengoshow** [comment]
I had to go back to using the getContent API call: if you're using
"find_category" when listing articles, then "_ _ category _ _" only returns
one Category instead of all the categories that article is assigned to. "_
_ categoryX _ _, " will list them all.

On Thu, Aug 27, 2015 at 11:53 AM, Chris Ullyott <notifications@github.com>
wrote:

> @bengoshow <https://github.com/bengoshow> Actually I haven't been able to
> work around this yet. getContent() repeats the line for any X tag, and
> currently I have only added a sequence number to differentiate them.
>
> Array
> (
>     [0] => Array
>         (
>             [title] => Love, Forgiveness, and Jesus
>             [slug] => love-forgiveness-and-jesus
>             [date] => 2010-12-06
>             [category1] => News
>             [category2] => Test
>         )
> )
>
> Using the plain category tag though, a list should be produced anyway:
>
> Array
> (
>     [0] => Array
>         (
>             [title] => Love, Forgiveness, and Jesus
>             [slug] => love-forgiveness-and-jesus
>             [date] => 2010-12-06
>             [category] => News, Test
>         )
> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MonkDev/monkcms-snippets/issues/18#issuecomment-135476044>
> .
>



-- 
*Ben Goshow*
e-Strategist | Fishhook
317.571.FISH {3474} x105  |  ben@fishhook.us  |  fishhook.us
*10609 North Park Avenue  |  Indianapolis, IN 46280*

*FREE RESOURCE:** Fishhook's NEW 2015 Webinars
<http://fishhook.us/2015-webinars> *| *Because who you are and the work you
do matters.*
