### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by pauldavidmoran** [MonkDev/monkcms-snippets#19]
When I upload the _export directory and set permissions to 775 and go to www.mysite.com/_export I immediately get 500-ed.

Anyone have a second to let me know what's going wrong?

**Comment by skylerkatz** [comment]
Hi @pauldavidmoran I work in support at Monk and would love to help you out.

Would you mind telling me the url of the site you are working on or you email address that is associated with your account in Ekklesia360?

**Comment by chrisullyott** [comment]
Woops, this was resolved in a Desk case.
